// Generated by gencpp from file gp9_path_planning/PathList.msg
// DO NOT EDIT!


#ifndef GP9_PATH_PLANNING_MESSAGE_PATHLIST_H
#define GP9_PATH_PLANNING_MESSAGE_PATHLIST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <geometry_msgs/Pose2D.h>

namespace gp9_path_planning
{
template <class ContainerAllocator>
struct PathList_
{
  typedef PathList_<ContainerAllocator> Type;

  PathList_()
    : header()
    , list()  {
    }
  PathList_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , list(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _list_type;
  _list_type list;





  typedef boost::shared_ptr< ::gp9_path_planning::PathList_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::gp9_path_planning::PathList_<ContainerAllocator> const> ConstPtr;

}; // struct PathList_

typedef ::gp9_path_planning::PathList_<std::allocator<void> > PathList;

typedef boost::shared_ptr< ::gp9_path_planning::PathList > PathListPtr;
typedef boost::shared_ptr< ::gp9_path_planning::PathList const> PathListConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::gp9_path_planning::PathList_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::gp9_path_planning::PathList_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace gp9_path_planning

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'gp9_path_planning': ['/home/ras29/catkin_ws/src/gp9_path_planning/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::gp9_path_planning::PathList_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::gp9_path_planning::PathList_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gp9_path_planning::PathList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::gp9_path_planning::PathList_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gp9_path_planning::PathList_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::gp9_path_planning::PathList_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::gp9_path_planning::PathList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "73778bfb1ad292de1879ee4eba0deb12";
  }

  static const char* value(const ::gp9_path_planning::PathList_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x73778bfb1ad292deULL;
  static const uint64_t static_value2 = 0x1879ee4eba0deb12ULL;
};

template<class ContainerAllocator>
struct DataType< ::gp9_path_planning::PathList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "gp9_path_planning/PathList";
  }

  static const char* value(const ::gp9_path_planning::PathList_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::gp9_path_planning::PathList_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
geometry_msgs/Pose2D[] list\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose2D\n\
# This expresses a position and orientation on a 2D manifold.\n\
\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::gp9_path_planning::PathList_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::gp9_path_planning::PathList_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.list);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PathList_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::gp9_path_planning::PathList_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::gp9_path_planning::PathList_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "list[]" << std::endl;
    for (size_t i = 0; i < v.list.size(); ++i)
    {
      s << indent << "  list[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.list[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // GP9_PATH_PLANNING_MESSAGE_PATHLIST_H
