// Generated by gencpp from file ras_lab1_msgs/ADConverter.msg
// DO NOT EDIT!


#ifndef RAS_LAB1_MSGS_MESSAGE_ADCONVERTER_H
#define RAS_LAB1_MSGS_MESSAGE_ADCONVERTER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ras_lab1_msgs
{
template <class ContainerAllocator>
struct ADConverter_
{
  typedef ADConverter_<ContainerAllocator> Type;

  ADConverter_()
    : ch1(0)
    , ch2(0)
    , ch3(0)
    , ch4(0)
    , ch5(0)
    , ch6(0)
    , ch7(0)
    , ch8(0)  {
    }
  ADConverter_(const ContainerAllocator& _alloc)
    : ch1(0)
    , ch2(0)
    , ch3(0)
    , ch4(0)
    , ch5(0)
    , ch6(0)
    , ch7(0)
    , ch8(0)  {
  (void)_alloc;
    }



   typedef uint16_t _ch1_type;
  _ch1_type ch1;

   typedef uint16_t _ch2_type;
  _ch2_type ch2;

   typedef uint16_t _ch3_type;
  _ch3_type ch3;

   typedef uint16_t _ch4_type;
  _ch4_type ch4;

   typedef uint16_t _ch5_type;
  _ch5_type ch5;

   typedef uint16_t _ch6_type;
  _ch6_type ch6;

   typedef uint16_t _ch7_type;
  _ch7_type ch7;

   typedef uint16_t _ch8_type;
  _ch8_type ch8;





  typedef boost::shared_ptr< ::ras_lab1_msgs::ADConverter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ras_lab1_msgs::ADConverter_<ContainerAllocator> const> ConstPtr;

}; // struct ADConverter_

typedef ::ras_lab1_msgs::ADConverter_<std::allocator<void> > ADConverter;

typedef boost::shared_ptr< ::ras_lab1_msgs::ADConverter > ADConverterPtr;
typedef boost::shared_ptr< ::ras_lab1_msgs::ADConverter const> ADConverterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ras_lab1_msgs::ADConverter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ras_lab1_msgs::ADConverter_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ras_lab1_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ras_lab1_msgs': ['/home/ras29/catkin_ws/src/ras_lab1/ras_lab1_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ras_lab1_msgs::ADConverter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ras_lab1_msgs::ADConverter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ras_lab1_msgs::ADConverter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ras_lab1_msgs::ADConverter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ras_lab1_msgs::ADConverter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ras_lab1_msgs::ADConverter_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ras_lab1_msgs::ADConverter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a5aa1c52a7841be08d11353384df8a9c";
  }

  static const char* value(const ::ras_lab1_msgs::ADConverter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa5aa1c52a7841be0ULL;
  static const uint64_t static_value2 = 0x8d11353384df8a9cULL;
};

template<class ContainerAllocator>
struct DataType< ::ras_lab1_msgs::ADConverter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ras_lab1_msgs/ADConverter";
  }

  static const char* value(const ::ras_lab1_msgs::ADConverter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ras_lab1_msgs::ADConverter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# 8 * uint16 for IR sensors\n\
uint16 ch1\n\
uint16 ch2\n\
uint16 ch3\n\
uint16 ch4\n\
uint16 ch5\n\
uint16 ch6\n\
uint16 ch7\n\
uint16 ch8\n\
\n\
\n\
";
  }

  static const char* value(const ::ras_lab1_msgs::ADConverter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ras_lab1_msgs::ADConverter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ch1);
      stream.next(m.ch2);
      stream.next(m.ch3);
      stream.next(m.ch4);
      stream.next(m.ch5);
      stream.next(m.ch6);
      stream.next(m.ch7);
      stream.next(m.ch8);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ADConverter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ras_lab1_msgs::ADConverter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ras_lab1_msgs::ADConverter_<ContainerAllocator>& v)
  {
    s << indent << "ch1: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ch1);
    s << indent << "ch2: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ch2);
    s << indent << "ch3: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ch3);
    s << indent << "ch4: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ch4);
    s << indent << "ch5: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ch5);
    s << indent << "ch6: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ch6);
    s << indent << "ch7: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ch7);
    s << indent << "ch8: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.ch8);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAS_LAB1_MSGS_MESSAGE_ADCONVERTER_H
