// Generated by gencpp from file ras_lab1_msgs/ServoMotors.msg
// DO NOT EDIT!


#ifndef RAS_LAB1_MSGS_MESSAGE_SERVOMOTORS_H
#define RAS_LAB1_MSGS_MESSAGE_SERVOMOTORS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ras_lab1_msgs
{
template <class ContainerAllocator>
struct ServoMotors_
{
  typedef ServoMotors_<ContainerAllocator> Type;

  ServoMotors_()
    : servo1(0)
    , servoangle()  {
      servoangle.assign(0);
  }
  ServoMotors_(const ContainerAllocator& _alloc)
    : servo1(0)
    , servoangle()  {
  (void)_alloc;
      servoangle.assign(0);
  }



   typedef uint8_t _servo1_type;
  _servo1_type servo1;

   typedef boost::array<uint8_t, 8>  _servoangle_type;
  _servoangle_type servoangle;





  typedef boost::shared_ptr< ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> const> ConstPtr;

}; // struct ServoMotors_

typedef ::ras_lab1_msgs::ServoMotors_<std::allocator<void> > ServoMotors;

typedef boost::shared_ptr< ::ras_lab1_msgs::ServoMotors > ServoMotorsPtr;
typedef boost::shared_ptr< ::ras_lab1_msgs::ServoMotors const> ServoMotorsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ras_lab1_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'ras_lab1_msgs': ['/home/ras19/catkin_ws/src/ras_lab1/ras_lab1_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f51d948c20e299a516b60c1bba9b447f";
  }

  static const char* value(const ::ras_lab1_msgs::ServoMotors_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf51d948c20e299a5ULL;
  static const uint64_t static_value2 = 0x16b60c1bba9b447fULL;
};

template<class ContainerAllocator>
struct DataType< ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ras_lab1_msgs/ServoMotors";
  }

  static const char* value(const ::ras_lab1_msgs::ServoMotors_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# desired angular position\n\
# range 0-180 degrees\n\
\n\
uint8 servo1\n\
uint8[8] servoangle\n\
";
  }

  static const char* value(const ::ras_lab1_msgs::ServoMotors_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.servo1);
      stream.next(m.servoangle);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ServoMotors_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ras_lab1_msgs::ServoMotors_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ras_lab1_msgs::ServoMotors_<ContainerAllocator>& v)
  {
    s << indent << "servo1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.servo1);
    s << indent << "servoangle[]" << std::endl;
    for (size_t i = 0; i < v.servoangle.size(); ++i)
    {
      s << indent << "  servoangle[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.servoangle[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // RAS_LAB1_MSGS_MESSAGE_SERVOMOTORS_H
