// Generated by gencpp from file phidgets/interface_kit.msg
// DO NOT EDIT!


#ifndef PHIDGETS_MESSAGE_INTERFACE_KIT_H
#define PHIDGETS_MESSAGE_INTERFACE_KIT_H

#include <ros/service_traits.h>


#include <phidgets/interface_kitRequest.h>
#include <phidgets/interface_kitResponse.h>


namespace phidgets
{

struct interface_kit
{

typedef interface_kitRequest Request;
typedef interface_kitResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct interface_kit
} // namespace phidgets


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::phidgets::interface_kit > {
  static const char* value()
  {
    return "75cbd2a6abfcf442181c14de3598b662";
  }

  static const char* value(const ::phidgets::interface_kit&) { return value(); }
};

template<>
struct DataType< ::phidgets::interface_kit > {
  static const char* value()
  {
    return "phidgets/interface_kit";
  }

  static const char* value(const ::phidgets::interface_kit&) { return value(); }
};


// service_traits::MD5Sum< ::phidgets::interface_kitRequest> should match 
// service_traits::MD5Sum< ::phidgets::interface_kit > 
template<>
struct MD5Sum< ::phidgets::interface_kitRequest>
{
  static const char* value()
  {
    return MD5Sum< ::phidgets::interface_kit >::value();
  }
  static const char* value(const ::phidgets::interface_kitRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::phidgets::interface_kitRequest> should match 
// service_traits::DataType< ::phidgets::interface_kit > 
template<>
struct DataType< ::phidgets::interface_kitRequest>
{
  static const char* value()
  {
    return DataType< ::phidgets::interface_kit >::value();
  }
  static const char* value(const ::phidgets::interface_kitRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::phidgets::interface_kitResponse> should match 
// service_traits::MD5Sum< ::phidgets::interface_kit > 
template<>
struct MD5Sum< ::phidgets::interface_kitResponse>
{
  static const char* value()
  {
    return MD5Sum< ::phidgets::interface_kit >::value();
  }
  static const char* value(const ::phidgets::interface_kitResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::phidgets::interface_kitResponse> should match 
// service_traits::DataType< ::phidgets::interface_kit > 
template<>
struct DataType< ::phidgets::interface_kitResponse>
{
  static const char* value()
  {
    return DataType< ::phidgets::interface_kit >::value();
  }
  static const char* value(const ::phidgets::interface_kitResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PHIDGETS_MESSAGE_INTERFACE_KIT_H
