// Generated by gencpp from file phidgets/interface_kitRequest.msg
// DO NOT EDIT!


#ifndef PHIDGETS_MESSAGE_INTERFACE_KITREQUEST_H
#define PHIDGETS_MESSAGE_INTERFACE_KITREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace phidgets
{
template <class ContainerAllocator>
struct interface_kitRequest_
{
  typedef interface_kitRequest_<ContainerAllocator> Type;

  interface_kitRequest_()
    : index(0)
    , value_type(0)
    , value(0)  {
    }
  interface_kitRequest_(const ContainerAllocator& _alloc)
    : index(0)
    , value_type(0)
    , value(0)  {
  (void)_alloc;
    }



   typedef int32_t _index_type;
  _index_type index;

   typedef int32_t _value_type_type;
  _value_type_type value_type;

   typedef int32_t _value_type;
  _value_type value;





  typedef boost::shared_ptr< ::phidgets::interface_kitRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets::interface_kitRequest_<ContainerAllocator> const> ConstPtr;

}; // struct interface_kitRequest_

typedef ::phidgets::interface_kitRequest_<std::allocator<void> > interface_kitRequest;

typedef boost::shared_ptr< ::phidgets::interface_kitRequest > interface_kitRequestPtr;
typedef boost::shared_ptr< ::phidgets::interface_kitRequest const> interface_kitRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phidgets::interface_kitRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phidgets::interface_kitRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace phidgets

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'phidgets': ['/home/ras29/catkin_ws/src/ras_project/ras_phidget/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::phidgets::interface_kitRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phidgets::interface_kitRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets::interface_kitRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets::interface_kitRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets::interface_kitRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets::interface_kitRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phidgets::interface_kitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "225c9deaf4e7ddb1539c5a9bdaa7a28f";
  }

  static const char* value(const ::phidgets::interface_kitRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x225c9deaf4e7ddb1ULL;
  static const uint64_t static_value2 = 0x539c5a9bdaa7a28fULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets::interface_kitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phidgets/interface_kitRequest";
  }

  static const char* value(const ::phidgets::interface_kitRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phidgets::interface_kitRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32 index\n\
int32 value_type\n\
int32 value\n\
";
  }

  static const char* value(const ::phidgets::interface_kitRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phidgets::interface_kitRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.index);
      stream.next(m.value_type);
      stream.next(m.value);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct interface_kitRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets::interface_kitRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phidgets::interface_kitRequest_<ContainerAllocator>& v)
  {
    s << indent << "index: ";
    Printer<int32_t>::stream(s, indent + "  ", v.index);
    s << indent << "value_type: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value_type);
    s << indent << "value: ";
    Printer<int32_t>::stream(s, indent + "  ", v.value);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_MESSAGE_INTERFACE_KITREQUEST_H
