// Generated by gencpp from file phidgets/motor_encoder.msg
// DO NOT EDIT!


#ifndef PHIDGETS_MESSAGE_MOTOR_ENCODER_H
#define PHIDGETS_MESSAGE_MOTOR_ENCODER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace phidgets
{
template <class ContainerAllocator>
struct motor_encoder_
{
  typedef motor_encoder_<ContainerAllocator> Type;

  motor_encoder_()
    : header()
    , count(0)
    , count_change(0)  {
    }
  motor_encoder_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , count(0)
    , count_change(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int32_t _count_type;
  _count_type count;

   typedef int32_t _count_change_type;
  _count_change_type count_change;





  typedef boost::shared_ptr< ::phidgets::motor_encoder_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::phidgets::motor_encoder_<ContainerAllocator> const> ConstPtr;

}; // struct motor_encoder_

typedef ::phidgets::motor_encoder_<std::allocator<void> > motor_encoder;

typedef boost::shared_ptr< ::phidgets::motor_encoder > motor_encoderPtr;
typedef boost::shared_ptr< ::phidgets::motor_encoder const> motor_encoderConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::phidgets::motor_encoder_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::phidgets::motor_encoder_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace phidgets

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'phidgets': ['/home/ras29/catkin_ws/src/ras_project/ras_phidget/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::phidgets::motor_encoder_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::phidgets::motor_encoder_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets::motor_encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::phidgets::motor_encoder_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets::motor_encoder_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::phidgets::motor_encoder_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::phidgets::motor_encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "37e1a519f128a6f4927cf6b14a5ffb50";
  }

  static const char* value(const ::phidgets::motor_encoder_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x37e1a519f128a6f4ULL;
  static const uint64_t static_value2 = 0x927cf6b14a5ffb50ULL;
};

template<class ContainerAllocator>
struct DataType< ::phidgets::motor_encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "phidgets/motor_encoder";
  }

  static const char* value(const ::phidgets::motor_encoder_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::phidgets::motor_encoder_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int32 count\n\
int32 count_change\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::phidgets::motor_encoder_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::phidgets::motor_encoder_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.count);
      stream.next(m.count_change);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct motor_encoder_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::phidgets::motor_encoder_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::phidgets::motor_encoder_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "count: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count);
    s << indent << "count_change: ";
    Printer<int32_t>::stream(s, indent + "  ", v.count_change);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PHIDGETS_MESSAGE_MOTOR_ENCODER_H
