// Generated by gencpp from file uarm/AttachDetachRequest.msg
// DO NOT EDIT!


#ifndef UARM_MESSAGE_ATTACHDETACHREQUEST_H
#define UARM_MESSAGE_ATTACHDETACHREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uarm
{
template <class ContainerAllocator>
struct AttachDetachRequest_
{
  typedef AttachDetachRequest_<ContainerAllocator> Type;

  AttachDetachRequest_()
    : attach(false)  {
    }
  AttachDetachRequest_(const ContainerAllocator& _alloc)
    : attach(false)  {
  (void)_alloc;
    }



   typedef uint8_t _attach_type;
  _attach_type attach;





  typedef boost::shared_ptr< ::uarm::AttachDetachRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uarm::AttachDetachRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AttachDetachRequest_

typedef ::uarm::AttachDetachRequest_<std::allocator<void> > AttachDetachRequest;

typedef boost::shared_ptr< ::uarm::AttachDetachRequest > AttachDetachRequestPtr;
typedef boost::shared_ptr< ::uarm::AttachDetachRequest const> AttachDetachRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uarm::AttachDetachRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uarm::AttachDetachRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uarm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uarm::AttachDetachRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uarm::AttachDetachRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uarm::AttachDetachRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uarm::AttachDetachRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uarm::AttachDetachRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uarm::AttachDetachRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uarm::AttachDetachRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4c9c23f471124df2ba7b8aa21eb56fe";
  }

  static const char* value(const ::uarm::AttachDetachRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4c9c23f471124dfULL;
  static const uint64_t static_value2 = 0x2ba7b8aa21eb56feULL;
};

template<class ContainerAllocator>
struct DataType< ::uarm::AttachDetachRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uarm/AttachDetachRequest";
  }

  static const char* value(const ::uarm::AttachDetachRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uarm::AttachDetachRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool attach\n\
\n\
";
  }

  static const char* value(const ::uarm::AttachDetachRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uarm::AttachDetachRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.attach);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AttachDetachRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uarm::AttachDetachRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uarm::AttachDetachRequest_<ContainerAllocator>& v)
  {
    s << indent << "attach: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.attach);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UARM_MESSAGE_ATTACHDETACHREQUEST_H
