// Generated by gencpp from file uarm/PumpResponse.msg
// DO NOT EDIT!


#ifndef UARM_MESSAGE_PUMPRESPONSE_H
#define UARM_MESSAGE_PUMPRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace uarm
{
template <class ContainerAllocator>
struct PumpResponse_
{
  typedef PumpResponse_<ContainerAllocator> Type;

  PumpResponse_()
    : pump_status(false)  {
    }
  PumpResponse_(const ContainerAllocator& _alloc)
    : pump_status(false)  {
  (void)_alloc;
    }



   typedef uint8_t _pump_status_type;
  _pump_status_type pump_status;





  typedef boost::shared_ptr< ::uarm::PumpResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uarm::PumpResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PumpResponse_

typedef ::uarm::PumpResponse_<std::allocator<void> > PumpResponse;

typedef boost::shared_ptr< ::uarm::PumpResponse > PumpResponsePtr;
typedef boost::shared_ptr< ::uarm::PumpResponse const> PumpResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uarm::PumpResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uarm::PumpResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uarm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uarm::PumpResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uarm::PumpResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uarm::PumpResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uarm::PumpResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uarm::PumpResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uarm::PumpResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uarm::PumpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7f77d32e62bdec27de7408effdd28bd9";
  }

  static const char* value(const ::uarm::PumpResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7f77d32e62bdec27ULL;
  static const uint64_t static_value2 = 0xde7408effdd28bd9ULL;
};

template<class ContainerAllocator>
struct DataType< ::uarm::PumpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uarm/PumpResponse";
  }

  static const char* value(const ::uarm::PumpResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uarm::PumpResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
bool pump_status\n\
\n\
";
  }

  static const char* value(const ::uarm::PumpResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uarm::PumpResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pump_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PumpResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uarm::PumpResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uarm::PumpResponse_<ContainerAllocator>& v)
  {
    s << indent << "pump_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.pump_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UARM_MESSAGE_PUMPRESPONSE_H
