(cl:in-package uarm-srv)
(cl:export '(J0-VAL
          J0
          J1-VAL
          J1
          J2-VAL
          J2
          J3-VAL
          J3
          MOVE_MODE-VAL
          MOVE_MODE
          MOVEMENT_DURATION-VAL
          MOVEMENT_DURATION
          INTERPOLATION_TYPE-VAL
          INTERPOLATION_TYPE
          CHECK_LIMITS-VAL
          CHECK_LIMITS
          J0-VAL
          J0
          J1-VAL
          J1
          J2-VAL
          J2
          J3-VAL
          J3
          ELAPSED-VAL
          ELAPSED
          ERROR-VAL
          ERROR
))