# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uarm/MoveToRequest.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import genpy

class MoveToRequest(genpy.Message):
  _md5sum = "ab030bae93172a56ee5d849ac8b8bebb"
  _type = "uarm/MoveToRequest"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
geometry_msgs/Point position
float32 eef_orientation
int32 move_mode
duration movement_duration
bool ignore_orientation
int32 interpolation_type
bool check_limits


int32 ABSOLUTE_MOVEMENT = 0
int32 RELATIVE_MOVEMENT = 1






int32 NO_INTERPOLATION = 0
int32 CUBIC_INTERPOLATION = 1
int32 LINEAR_INTERPOLATION = 2


================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  # Pseudo-constants
  ABSOLUTE_MOVEMENT = 0
  RELATIVE_MOVEMENT = 1
  NO_INTERPOLATION = 0
  CUBIC_INTERPOLATION = 1
  LINEAR_INTERPOLATION = 2

  __slots__ = ['position','eef_orientation','move_mode','movement_duration','ignore_orientation','interpolation_type','check_limits']
  _slot_types = ['geometry_msgs/Point','float32','int32','duration','bool','int32','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,eef_orientation,move_mode,movement_duration,ignore_orientation,interpolation_type,check_limits

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MoveToRequest, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.eef_orientation is None:
        self.eef_orientation = 0.
      if self.move_mode is None:
        self.move_mode = 0
      if self.movement_duration is None:
        self.movement_duration = genpy.Duration()
      if self.ignore_orientation is None:
        self.ignore_orientation = False
      if self.interpolation_type is None:
        self.interpolation_type = 0
      if self.check_limits is None:
        self.check_limits = False
    else:
      self.position = geometry_msgs.msg.Point()
      self.eef_orientation = 0.
      self.move_mode = 0
      self.movement_duration = genpy.Duration()
      self.ignore_orientation = False
      self.interpolation_type = 0
      self.check_limits = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3df3iBiB().pack(_x.position.x, _x.position.y, _x.position.z, _x.eef_orientation, _x.move_mode, _x.movement_duration.secs, _x.movement_duration.nsecs, _x.ignore_orientation, _x.interpolation_type, _x.check_limits))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.movement_duration is None:
        self.movement_duration = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 46
      (_x.position.x, _x.position.y, _x.position.z, _x.eef_orientation, _x.move_mode, _x.movement_duration.secs, _x.movement_duration.nsecs, _x.ignore_orientation, _x.interpolation_type, _x.check_limits,) = _get_struct_3df3iBiB().unpack(str[start:end])
      self.ignore_orientation = bool(self.ignore_orientation)
      self.check_limits = bool(self.check_limits)
      self.movement_duration.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3df3iBiB().pack(_x.position.x, _x.position.y, _x.position.z, _x.eef_orientation, _x.move_mode, _x.movement_duration.secs, _x.movement_duration.nsecs, _x.ignore_orientation, _x.interpolation_type, _x.check_limits))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.movement_duration is None:
        self.movement_duration = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 46
      (_x.position.x, _x.position.y, _x.position.z, _x.eef_orientation, _x.move_mode, _x.movement_duration.secs, _x.movement_duration.nsecs, _x.ignore_orientation, _x.interpolation_type, _x.check_limits,) = _get_struct_3df3iBiB().unpack(str[start:end])
      self.ignore_orientation = bool(self.ignore_orientation)
      self.check_limits = bool(self.check_limits)
      self.movement_duration.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3df3iBiB = None
def _get_struct_3df3iBiB():
    global _struct_3df3iBiB
    if _struct_3df3iBiB is None:
        _struct_3df3iBiB = struct.Struct("<3df3iBiB")
    return _struct_3df3iBiB
# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from uarm/MoveToResponse.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import genpy

class MoveToResponse(genpy.Message):
  _md5sum = "8f9784c5f3f87c5aee051029211ee037"
  _type = "uarm/MoveToResponse"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """
geometry_msgs/Point position
duration elapsed
bool error


================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['position','elapsed','error']
  _slot_types = ['geometry_msgs/Point','duration','bool']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       position,elapsed,error

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MoveToResponse, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.elapsed is None:
        self.elapsed = genpy.Duration()
      if self.error is None:
        self.error = False
    else:
      self.position = geometry_msgs.msg.Point()
      self.elapsed = genpy.Duration()
      self.error = False

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3d2iB().pack(_x.position.x, _x.position.y, _x.position.z, _x.elapsed.secs, _x.elapsed.nsecs, _x.error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.elapsed is None:
        self.elapsed = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.position.x, _x.position.y, _x.position.z, _x.elapsed.secs, _x.elapsed.nsecs, _x.error,) = _get_struct_3d2iB().unpack(str[start:end])
      self.error = bool(self.error)
      self.elapsed.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3d2iB().pack(_x.position.x, _x.position.y, _x.position.z, _x.elapsed.secs, _x.elapsed.nsecs, _x.error))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.position is None:
        self.position = geometry_msgs.msg.Point()
      if self.elapsed is None:
        self.elapsed = genpy.Duration()
      end = 0
      _x = self
      start = end
      end += 33
      (_x.position.x, _x.position.y, _x.position.z, _x.elapsed.secs, _x.elapsed.nsecs, _x.error,) = _get_struct_3d2iB().unpack(str[start:end])
      self.error = bool(self.error)
      self.elapsed.canon()
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_3d2iB = None
def _get_struct_3d2iB():
    global _struct_3d2iB
    if _struct_3d2iB is None:
        _struct_3d2iB = struct.Struct("<3d2iB")
    return _struct_3d2iB
class MoveTo(object):
  _type          = 'uarm/MoveTo'
  _md5sum = 'b5950699ca93b2e0816f732b4daecc97'
  _request_class  = MoveToRequest
  _response_class = MoveToResponse
