# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ras_lab1_msgs/BatteryStatus.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BatteryStatus(genpy.Message):
  _md5sum = "0cacd621f2d12e6814d77d4a2f6b6051"
  _type = "ras_lab1_msgs/BatteryStatus"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Say if battery is in use, of if a wall adaptator is present
# value : 1 if on battery, 0 if adaptator present
uint8 on_batt

# cell voltage
float32 cell1
float32 cell2
float32 cell3



"""
  __slots__ = ['on_batt','cell1','cell2','cell3']
  _slot_types = ['uint8','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       on_batt,cell1,cell2,cell3

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BatteryStatus, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.on_batt is None:
        self.on_batt = 0
      if self.cell1 is None:
        self.cell1 = 0.
      if self.cell2 is None:
        self.cell2 = 0.
      if self.cell3 is None:
        self.cell3 = 0.
    else:
      self.on_batt = 0
      self.cell1 = 0.
      self.cell2 = 0.
      self.cell3 = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_B3f().pack(_x.on_batt, _x.cell1, _x.cell2, _x.cell3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.on_batt, _x.cell1, _x.cell2, _x.cell3,) = _get_struct_B3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_B3f().pack(_x.on_batt, _x.cell1, _x.cell2, _x.cell3))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 13
      (_x.on_batt, _x.cell1, _x.cell2, _x.cell3,) = _get_struct_B3f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_B3f = None
def _get_struct_B3f():
    global _struct_B3f
    if _struct_B3f is None:
        _struct_B3f = struct.Struct("<B3f")
    return _struct_B3f
