# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from ras_lab1_msgs/Encoders.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Encoders(genpy.Message):
  _md5sum = "6363193e7f66cd2bf0e60c5eb25e1bd5"
  _type = "ras_lab1_msgs/Encoders"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# encoder: absolute encoder value
# delta_encoder: differential encoder value
# tiemstamp: in milliseconds
# 1 --> left
# 2 --> right
int32 encoder1
int32 encoder2
int32 delta_encoder1
int32 delta_encoder2
int32 timestamp

"""
  __slots__ = ['encoder1','encoder2','delta_encoder1','delta_encoder2','timestamp']
  _slot_types = ['int32','int32','int32','int32','int32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       encoder1,encoder2,delta_encoder1,delta_encoder2,timestamp

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Encoders, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.encoder1 is None:
        self.encoder1 = 0
      if self.encoder2 is None:
        self.encoder2 = 0
      if self.delta_encoder1 is None:
        self.delta_encoder1 = 0
      if self.delta_encoder2 is None:
        self.delta_encoder2 = 0
      if self.timestamp is None:
        self.timestamp = 0
    else:
      self.encoder1 = 0
      self.encoder2 = 0
      self.delta_encoder1 = 0
      self.delta_encoder2 = 0
      self.timestamp = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_5i().pack(_x.encoder1, _x.encoder2, _x.delta_encoder1, _x.delta_encoder2, _x.timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.encoder1, _x.encoder2, _x.delta_encoder1, _x.delta_encoder2, _x.timestamp,) = _get_struct_5i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_5i().pack(_x.encoder1, _x.encoder2, _x.delta_encoder1, _x.delta_encoder2, _x.timestamp))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.encoder1, _x.encoder2, _x.delta_encoder1, _x.delta_encoder2, _x.timestamp,) = _get_struct_5i().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_5i = None
def _get_struct_5i():
    global _struct_5i
    if _struct_5i is None:
        _struct_5i = struct.Struct("<5i")
    return _struct_5i
