// Generated by gencpp from file arduino_servo_control/SetServoAngles.msg
// DO NOT EDIT!


#ifndef ARDUINO_SERVO_CONTROL_MESSAGE_SETSERVOANGLES_H
#define ARDUINO_SERVO_CONTROL_MESSAGE_SETSERVOANGLES_H

#include <ros/service_traits.h>


#include <arduino_servo_control/SetServoAnglesRequest.h>
#include <arduino_servo_control/SetServoAnglesResponse.h>


namespace arduino_servo_control
{

struct SetServoAngles
{

typedef SetServoAnglesRequest Request;
typedef SetServoAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetServoAngles
} // namespace arduino_servo_control


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::arduino_servo_control::SetServoAngles > {
  static const char* value()
  {
    return "9f74ea09edde7d0924376ba2d9b77543";
  }

  static const char* value(const ::arduino_servo_control::SetServoAngles&) { return value(); }
};

template<>
struct DataType< ::arduino_servo_control::SetServoAngles > {
  static const char* value()
  {
    return "arduino_servo_control/SetServoAngles";
  }

  static const char* value(const ::arduino_servo_control::SetServoAngles&) { return value(); }
};


// service_traits::MD5Sum< ::arduino_servo_control::SetServoAnglesRequest> should match 
// service_traits::MD5Sum< ::arduino_servo_control::SetServoAngles > 
template<>
struct MD5Sum< ::arduino_servo_control::SetServoAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::arduino_servo_control::SetServoAngles >::value();
  }
  static const char* value(const ::arduino_servo_control::SetServoAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::arduino_servo_control::SetServoAnglesRequest> should match 
// service_traits::DataType< ::arduino_servo_control::SetServoAngles > 
template<>
struct DataType< ::arduino_servo_control::SetServoAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::arduino_servo_control::SetServoAngles >::value();
  }
  static const char* value(const ::arduino_servo_control::SetServoAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::arduino_servo_control::SetServoAnglesResponse> should match 
// service_traits::MD5Sum< ::arduino_servo_control::SetServoAngles > 
template<>
struct MD5Sum< ::arduino_servo_control::SetServoAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::arduino_servo_control::SetServoAngles >::value();
  }
  static const char* value(const ::arduino_servo_control::SetServoAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::arduino_servo_control::SetServoAnglesResponse> should match 
// service_traits::DataType< ::arduino_servo_control::SetServoAngles > 
template<>
struct DataType< ::arduino_servo_control::SetServoAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::arduino_servo_control::SetServoAngles >::value();
  }
  static const char* value(const ::arduino_servo_control::SetServoAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ARDUINO_SERVO_CONTROL_MESSAGE_SETSERVOANGLES_H
