// Generated by gencpp from file uarm/MoveTo.msg
// DO NOT EDIT!


#ifndef UARM_MESSAGE_MOVETO_H
#define UARM_MESSAGE_MOVETO_H

#include <ros/service_traits.h>


#include <uarm/MoveToRequest.h>
#include <uarm/MoveToResponse.h>


namespace uarm
{

struct MoveTo
{

typedef MoveToRequest Request;
typedef MoveToResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct MoveTo
} // namespace uarm


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::uarm::MoveTo > {
  static const char* value()
  {
    return "b5950699ca93b2e0816f732b4daecc97";
  }

  static const char* value(const ::uarm::MoveTo&) { return value(); }
};

template<>
struct DataType< ::uarm::MoveTo > {
  static const char* value()
  {
    return "uarm/MoveTo";
  }

  static const char* value(const ::uarm::MoveTo&) { return value(); }
};


// service_traits::MD5Sum< ::uarm::MoveToRequest> should match 
// service_traits::MD5Sum< ::uarm::MoveTo > 
template<>
struct MD5Sum< ::uarm::MoveToRequest>
{
  static const char* value()
  {
    return MD5Sum< ::uarm::MoveTo >::value();
  }
  static const char* value(const ::uarm::MoveToRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::uarm::MoveToRequest> should match 
// service_traits::DataType< ::uarm::MoveTo > 
template<>
struct DataType< ::uarm::MoveToRequest>
{
  static const char* value()
  {
    return DataType< ::uarm::MoveTo >::value();
  }
  static const char* value(const ::uarm::MoveToRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::uarm::MoveToResponse> should match 
// service_traits::MD5Sum< ::uarm::MoveTo > 
template<>
struct MD5Sum< ::uarm::MoveToResponse>
{
  static const char* value()
  {
    return MD5Sum< ::uarm::MoveTo >::value();
  }
  static const char* value(const ::uarm::MoveToResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::uarm::MoveToResponse> should match 
// service_traits::DataType< ::uarm::MoveTo > 
template<>
struct DataType< ::uarm::MoveToResponse>
{
  static const char* value()
  {
    return DataType< ::uarm::MoveTo >::value();
  }
  static const char* value(const ::uarm::MoveToResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UARM_MESSAGE_MOVETO_H
