// Generated by gencpp from file uarm/MoveToResponse.msg
// DO NOT EDIT!


#ifndef UARM_MESSAGE_MOVETORESPONSE_H
#define UARM_MESSAGE_MOVETORESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace uarm
{
template <class ContainerAllocator>
struct MoveToResponse_
{
  typedef MoveToResponse_<ContainerAllocator> Type;

  MoveToResponse_()
    : position()
    , elapsed()
    , error(false)  {
    }
  MoveToResponse_(const ContainerAllocator& _alloc)
    : position(_alloc)
    , elapsed()
    , error(false)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _position_type;
  _position_type position;

   typedef ros::Duration _elapsed_type;
  _elapsed_type elapsed;

   typedef uint8_t _error_type;
  _error_type error;





  typedef boost::shared_ptr< ::uarm::MoveToResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::uarm::MoveToResponse_<ContainerAllocator> const> ConstPtr;

}; // struct MoveToResponse_

typedef ::uarm::MoveToResponse_<std::allocator<void> > MoveToResponse;

typedef boost::shared_ptr< ::uarm::MoveToResponse > MoveToResponsePtr;
typedef boost::shared_ptr< ::uarm::MoveToResponse const> MoveToResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::uarm::MoveToResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::uarm::MoveToResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace uarm

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::uarm::MoveToResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::uarm::MoveToResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uarm::MoveToResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::uarm::MoveToResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uarm::MoveToResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::uarm::MoveToResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::uarm::MoveToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8f9784c5f3f87c5aee051029211ee037";
  }

  static const char* value(const ::uarm::MoveToResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8f9784c5f3f87c5aULL;
  static const uint64_t static_value2 = 0xee051029211ee037ULL;
};

template<class ContainerAllocator>
struct DataType< ::uarm::MoveToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uarm/MoveToResponse";
  }

  static const char* value(const ::uarm::MoveToResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::uarm::MoveToResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
geometry_msgs/Point position\n\
duration elapsed\n\
bool error\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::uarm::MoveToResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::uarm::MoveToResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position);
      stream.next(m.elapsed);
      stream.next(m.error);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MoveToResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::uarm::MoveToResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::uarm::MoveToResponse_<ContainerAllocator>& v)
  {
    s << indent << "position: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.position);
    s << indent << "elapsed: ";
    Printer<ros::Duration>::stream(s, indent + "  ", v.elapsed);
    s << indent << "error: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.error);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UARM_MESSAGE_MOVETORESPONSE_H
