// Generated by gencpp from file arduino_servo_control/SetServoAnglesResponse.msg
// DO NOT EDIT!


#ifndef ARDUINO_SERVO_CONTROL_MESSAGE_SETSERVOANGLESRESPONSE_H
#define ARDUINO_SERVO_CONTROL_MESSAGE_SETSERVOANGLESRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arduino_servo_control
{
template <class ContainerAllocator>
struct SetServoAnglesResponse_
{
  typedef SetServoAnglesResponse_<ContainerAllocator> Type;

  SetServoAnglesResponse_()
    : success(false)  {
    }
  SetServoAnglesResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SetServoAnglesResponse_

typedef ::arduino_servo_control::SetServoAnglesResponse_<std::allocator<void> > SetServoAnglesResponse;

typedef boost::shared_ptr< ::arduino_servo_control::SetServoAnglesResponse > SetServoAnglesResponsePtr;
typedef boost::shared_ptr< ::arduino_servo_control::SetServoAnglesResponse const> SetServoAnglesResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arduino_servo_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arduino_servo_control/SetServoAnglesResponse";
  }

  static const char* value(const ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n\
\n\
";
  }

  static const char* value(const ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SetServoAnglesResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arduino_servo_control::SetServoAnglesResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARDUINO_SERVO_CONTROL_MESSAGE_SETSERVOANGLESRESPONSE_H
